### ISSUE TITLE
Cannot instantiate the custom serializer/deserializer

### ISSUE THREAD

**Issue by hellofornow** [nmorel/gwt-jackson#58]
I'm trying to create a custom deserializer (for Enum.class).

I have followed the steps in the wiki article, however any custom serializer/deserializer I try and register throws a similar unable to instantiate error:

[INFO]          Invoking generator com.github.nmorel.gwtjackson.rebind.ObjectMapperGenerator
[INFO]             [WARN] Cannot instantiate the custom serializer/deserializer com.github.nmorel.gwtjackson.client.ser.EnumJsonSerializer. It will be ignored
[INFO]             [WARN] Cannot instantiate the custom serializer/deserializer com.caseware.cloud.client.dispatch.CustomEnumDeserializer. It will be ignored

This is what my gwtjackson.configuration.extension class looks like:
```java
public final class CustomDeserializer extends AbstractConfiguration {
    @Override
    protected void configure() {
        type(Enum.class).deserializer(CustomEnumDeserializer.class);
    }
}
```
This is what CustomEnumDeserializer looks like:
```java
public class CustomEnumDeserializer<E extends Enum<E>> extends JsonDeserializer<E> {

    private final Class<E> enumClass;

    /**
     * @param enumClass class of the enumeration
     */
    protected CustomEnumDeserializer(Class<E> enumClass) {
        if (null == enumClass) {
            throw new IllegalArgumentException("enumClass cannot be null");
        }
        this.enumClass = enumClass;
    }


    /**
     * @param enumClass class of the enumeration
     * @param <E>       Type of the enum
     * @return a new instance of {@link CustomEnumDeserializer}
     */
    public static <E extends Enum<E>> CustomEnumDeserializer<E> newInstance(Class<E> enumClass) {
        return new CustomEnumDeserializer<E>(enumClass);
    }

    @Override
    public E doDeserialize(JsonReader reader, JsonDeserializationContext ctx, JsonDeserializerParameters params) {
        try {
            return Enum.valueOf(this.enumClass, reader.nextString());
        } catch (IllegalArgumentException ex) {            
            //return Enum.valueOf(this.enumClass, "UnknownEnumValue");
            //this is what I am customizing but may replace w/ commented out line above
             return null;
        }
    }
``` 
I have tried to override other types as well (String), same "Cannot instantiate" error occurs.

May be nice if gwt-jackson could support a similar feature as com.fasterxml.jackson.databind.ObjectMapper supports:
DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL

I would be willing to fork/create feature branch if it's something you agree w/. That being said I'm not sure I want to always return null. I am generating all my enums and may create an "UnknownEnumValue" that I return when IllegalArgumentException occurs (commented out above).

Cheers
PS: great library; really appreciate it!

**Comment by nmorel** [comment]
You tried to override the only type you cannot :)

If you look at `com.github.nmorel.gwtjackson.rebind.DefaultConfiguration`, `Enum` is the only commented type! 

Since Enum is parameterized, I'm looking for a constructor or static method taking a `JsonDeserializer<E>` like `ListJsonDeserializer` for example. Since enum requires a `Class<E>` and not a `JsonDeserializer<E>`, there is no suitable constructor found and that's why you see the log. 

To support the override, we need to : 
1. Add a specific case in `com.github.nmorel.gwtjackson.rebind.RebindConfiguration#getInstance` when the mapping type is `Enum` to look for constructor/static method taking a `Class<Enum>`
2. Update `com.github.nmorel.gwtjackson.rebind.AbstractCreator#getJsonDeserializerFromType` where I currently handle enum values to replace the use of `EnumJsonDeserializer.class` with the one present in configuration. It's like the JavaScriptObject handling.
3. Do the same in `com.github.nmorel.gwtjackson.rebind.AbstractCreator#getKeyDeserializerFromType`
4. Uncomment the lines in `com.github.nmorel.gwtjackson.rebind.DefaultConfiguration`

Adding support for `DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL` should not be too hard. 
1. Add the option to `JsonDeserializationContext`
2. Add a try/catch in `EnumJsonDeserializer` and `EnumKeyDeserializer` to return null if the config is true
3. Add a try/catch in all the enum collection deserializer to ignore the value if unknown as jackson do
4. Add a test!

Feel free to fork and submit a PR :)
