### ISSUE TITLE
GWT Compile Issues

### ISSUE THREAD

**Issue by yadavharsh** [nmorel/gwt-jackson#94]
Hi,

I am trying to migrate to the gwt-maven-plugin (net.ltgt.gwt.maven).

However, with gwtjackon am not able to include the jackson annotation sources thru maven dependencies.
```
[INFO]    Tracing compile failure path for type 'com.fasterxml.jackson.annotation.JsonIgnoreProperties'
[INFO]       [ERROR] Errors in 'com/fasterxml/jackson/annotation/JsonIgnoreProperties.java'
[INFO]          [ERROR] Line 374: The method format(String, Set<String>, boolean, boolean, boolean, boolean) is undefined for the type String
```

This used to work seamlessly with the mojos gwt plugin before by including the following dependency:

```
<dependency>
    <groupId>com.github.nmorel.gwtjackson</groupId>
    <artifactId>gwt-jackson</artifactId>
    <version>0.13.1-SNAPSHOT</version>
    <scope>provided</scope>
</dependency>
```

With the new maven plugin, I am adding dependencies like:
```
<dependency>
    <groupId>com.github.nmorel.gwtjackson</groupId>
    <artifactId>gwt-jackson</artifactId>
    <version>0.13.1-SNAPSHOT</version>
</dependency>
```

And then in my *.gwt.xml

`<inherits name="com.github.nmorel.gwtjackson.GwtJackson"/>
`
I also tried to explicitly include the jackson annotations so sources are available and GWT compiler doesn't complain:
```
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.8.2</version>
    <classifier>sources</classifier>
</dependency>
```

Still no luck.

Can you suggest any workaround for this?

**Comment by nmorel** [comment]
The problem is not the inclusion of the annotations. It sees them and fails on one.  
[The source of the failing annotation](https://github.com/FasterXML/jackson-annotations/blob/master/src/main/java/com/fasterxml/jackson/annotation/JsonIgnoreProperties.java#L374)  
In the subclass Value, the toString method is using String.format that does not exist in GWT. 
For a workaround, you can supersource this annotation and remove the Value class completely (or just the toString method).  
I already did that for [JsonInclude](https://github.com/nmorel/gwt-jackson/blob/master/gwt-jackson/src/main/resources/com/github/nmorel/gwtjackson/super/com/fasterxml/jackson/annotation/JsonInclude.java)  

If I have time tonight, I'll add it.  

You can also use a 2.7.x version of Jackson. The Value has been added in 2.8.

**Comment by yadavharsh** [comment]
Yes, I did that. And the work around works fine for me now.
(Removing the reference for String.format)

Thanks a lot, gwtjackson works perfectly!
